project:
  type: website
  output-dir: docs 
  
website:
  title: "Welcome!"
  navbar:
    left:
      - href: about.qmd
        text: Home
      - research.qmd
      - teaching.qmd
      - blog_post.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

