project:
  type: website
  output-dir: docs 
  
website:
  title: "Welcome!"
  navbar: 
    left: 
      - href: about.qmd
        text: Home
      - href: research.qmd
        text: Reseach
      - href: teaching.qmd
        text: Teaching
      - href: blog_post.qmd
        text: Blog Post
    background: dark
    foreground: light
  search: false
  
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

