project:
  type: website
  output-dir: docs 
  
website:
  title: "Home"
  navbar: 
    left: 
      - href: research.qmd
        text: Reseach
      - href: experience.qmd
        text: Experience
      - href: blog_post.qmd
        text: Blog Post
    background: dark
    foreground: light
  search: false
  
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

